### ISSUE TITLE
sanitize_utf8: Assertion `u8_check` consistently fails

### ISSUE THREAD

**Issue by zakird** [zmap/zmap#335] opened 2016-03-20 12:00 UTC
src/fieldset.c:162: sanitize_utf8: throws this assertion `u8_check((uint8_t*)safe_buf, strlen(safe_buf)) == ((void *)0)' failed.` every time we run a UPnP scan. 

We need to either fix utf8 sanitization, or remove it and find a different solution.

**Comment by zakird** [comment] 2016-03-20 12:01
@paul-pearce assigning to you for your thoughts.

**Comment by zakird** [comment] 2016-06-25 09:54
@paul-pearce any ideas what's going on here? I'd like to figure out some way of resolving with without pulling out the UTF-8 sanitization code from ZMap.

**Comment by paul-pearce** [comment] 2016-10-21 00:58
As discussed offline: This seems to resolve under ubuntu 16.04. We are also having trouble recreating it consistently under 14.04. We're going to run some more tests but may write this off as an will not fix under 14.04.

**Comment by paul-pearce** [comment] 2016-12-06 01:33
Dug into this further. I could find no cause for this failing under 14.04 vs 16.04. The package diffs yielded no obvious answers. Since this could never be reproduced outside the old umich infrastructure and went away on system upgrade, I'm not sure what the ultimate cause was. I'm going to close this issue for now.

As an aside: the ubuntu packages are extremely old (<6 years, even redhat el7 is newer). If this pops up again I'm going to look into migrating to a different library.

**Closed by paul-pearce** 2016-12-06 01:33 UTC
Labels: bug
