### ISSUE TITLE
Must specify both rate and bandwidth when limiting scan by bandwidth

### ISSUE THREAD

**Issue by jhart-r7** [zmap/zmap#553] opened 2019-04-30 16:56 UTC
As far as I can tell this was introduced via https://github.com/zmap/zmap/pull/530.  Now if you want to set the maximum bandwidth to be used by a scan you'll receive an error:

```
$  ./src/zmap -p 443 -i en0 -e 1 -T 1  -B 10m  -d -G 00:00:00:00:00:00 -n 2  -v 5 2>&1 | grep rate
Apr 30 09:23:00.034 [FATAL] send: must specify rate or bandwidth, or neither, not both.
```

The workaround is slightly confusing because you need to specify a rate of 0 despite what the error message says:

```
$  ./src/zmap -p 443 -i en0 -e 1 -T 1  -B 10m -r 0  -d -G 00:00:00:00:00:00 -n 2  -v 5 2>&1 | grep rate
Apr 30 09:56:13.688 [DEBUG] send: using bandwidth 10000000 bits/s for 84 byte probe, rate set to 14880 pkt/s
```

Further possible confusion comes from the documentation for `-r`:

```
Setting the rate to 0 will scan at full line rate. Default: 10000 pps. 
```

When the rate is set to 0 but bandwidth is set, the rate will be calculated based on the specified bandwidth and will not be full line rate.

**Comment by zakird** [comment] 2019-05-01 05:16
I agree, it looks like the problem is the default value that gets installed to `/etc/zmap.conf`. I agree it probably makes sense to just move this value into the codebase.

**Comment by zakird** [comment] 2019-05-01 05:45
I think https://github.com/zmap/zmap/pull/555 should fix this.

**Comment by zakird** [comment] 2019-09-16 17:51
Closing sicne comment in 555 verifeis fix.

**Closed by zakird** 2019-09-16 17:51 UTC
