### ISSUE TITLE
CMake Error at InstallConfFiles.cmake:2 (file):   file COPY cannot find "/conf/blacklist.conf".

### ISSUE THREAD

**Issue by 312362115** [zmap/zmap#327] opened 2016-01-29 18:56 UTC
I build zmap from source. and I get a error:
"""
CMake Error at InstallConfFiles.cmake:2 (file):
  file COPY cannot find "/conf/blacklist.conf".
Call Stack (most recent call first):
  cmake_install.cmake:36 (include)
"""

in file InstallConfFiles.cmake:2,  COPY "${PROJECT_SOURCE_DIR}/conf/blacklist.conf"

maybe the ${PROJECT_SOURCE_DIR} is contains a '/'. so the path is like "zmap//conf/blacklist.conf".

I delete the "/", so it like: "${PROJECT_SOURCE_DIR}conf/blacklist.conf" and build success.

**Comment by dadrian** [comment] 2016-01-29 19:00
What was your original CMake command? Did you add a trailing slash to the directory name? I've never encountered this before.

**Comment by 312362115** [comment] 2016-01-29 19:03
cmake -DENABLE_DEVELOPMENT=OFF
make
make install

**Comment by dadrian** [comment] 2016-01-29 19:05
Try running `cmake -DENABLE_DEVELOPMENT=OFF .` from the root of the repository. Be sure to pass the trailing `.`.

**Comment by 312362115** [comment] 2016-01-29 19:10
I use `cmake -DENABLE_DEVELOPMENT=OFF .` but it still get a error
> CMake Error at InstallConfFiles.cmake:2 (file):
>   file COPY cannot find "/conf/blacklist.conf".

**Comment by ndacs** [comment] 2016-04-26 19:25
I met same problem on zmap-2.1.0.
'make' process was well worked, but 'make install' causes same error.
>> CMake Error at InstallConfFiles.cmake:2 (file):
due to that ${PROJECT_SOURCE_DIR} was never defined.

Is this happen based on version of OS or cmake?
I using following environment:
cmake version 3.5.2 & Mac OS Darwin 15.4.0

Well worked on:
cmake version 3.5.2 & CentOS 7

**Comment by zakird** [comment] 2016-06-25 10:01
Sorry for the delay in getting back to everyone. I just upgraded my came to 3.5.2, but I'm not able to reproduce this issue with master. I also double checked and `PROJECT_SOURCE_DIR` is a well defined variable within the CMAKE documentation. I suspect that this is an issue with your install of cmake. 

Does the same problem occur in the master branch?

**Comment by 312362115** [comment] 2016-06-27 02:06
I use Mac and install cmake use homebrew.

**Comment by dadrian** [comment] 2016-06-27 03:42
I can't seem to duplicate on OS X.

**Comment by MrliuSAMA** [comment] 2016-08-09 08:01
i also meet the problem same as @ndacs.

the error hint is :
==============start====================
~/sourcecode/zmap-2.1.0# make install
[ 21%] Built target zmaplib
[ 26%] Built target zblacklist
[ 94%] Built target zmap
[100%] Built target ztee
Install the project...
-- Install configuration: ""
CMake Error at InstallConfFiles.cmake:2 (file):
  file COPY cannot find "/conf/blacklist.conf".
Call Stack (most recent call first):
  cmake_install.cmake:36 (INCLUDE)

make: *** [install] Error 1
============end==================

i found the source coude:
file InstallConfFiles.cmake line 2, but didn't find ${PROJECT_SOURCE_DIR} wiere definded , could you help me?
@zakird

**Comment by MrliuSAMA** [comment] 2016-08-09 08:23
i messaged variable  ${PROJECT_SOURCE_DIR} find its value is null.
i wonder wherethe variable ${PROJECT_SOURCE_DIR} should be defined?

cmake version  & zmap version 2.1.0

**Comment by sm0k3net** [comment] 2016-09-21 12:46
I have found solution.

If you have problems with CMake and was need to install new one, you possibly running it like "/usr/local/bin/cmake" and here comes the problem with correct project directory detecting (maybe also actual for usual installation when cmake binary runs from /usr/bin/cmake).
Was need to edit "InstallConfFiles.cmake" in ZMap sources directory, fix line 2 and 6 for actual path.

When you in the zmap source directory, just type "pwd" and copy this route, than you will need to add it in "InstallConfFiles.cmake".

Change variable ${PROJECT_SOURCE_DIR} in both lines and all should work fine :)

Also, want to add additional hint for the problems with 'libjson' - if happens that you meeting errors while trying to make & install zmap, you need to go here: https://github.com/json-c/json-c
Need to install "json-c" , make all like written in the instruction including required dependencies.

I met problems on Debian 7.11 x32, after I have done all from my post above, things worked fine!

**Comment by dadrian** [comment] 2016-11-21 18:59
Does anyone still experience this on latest master with an up-to-date CMake install, or can I close this issue?

**Closed** 2016-12-04 20:41 UTC
Labels: support

**Comment by albinowax** [comment] 2017-02-27 14:08
I just hit this with zmap-2.1.0 and cmake version 2.8.12 (the latest available in the package manager)

@sm0k3net's workaround worked for me.
