### ISSUE TITLE
zmap can't run on BandwagonHost VPS

### ISSUE THREAD

**Issue by chuanjiesun** [zmap/zmap#398] opened 2016-12-07 11:56 UTC
I compiled zmap on BandwagonHost VPS and run zmap on it, but got an error " [FATAL] recv: couldn't compile filter",the OS is  centos6 2.6.32-042stab116.2 x86_64,How can I solve this problem?

**Comment by dadrian** [comment] 2016-12-07 15:25
It sounds like it couldn't create the receive packet filter, is your libpcap up to date? Are packet filters somehow disabled by your VPS provider?

**Comment by chuanjiesun** [comment] 2016-12-08 00:54
the libpcap version is "libpcap-devel-1.4.0-4.20130826git2dbcaa1.el6.x86_64",is that too old ?  and I will send an email to VPS provider to see if packet filters are disabled.

**Comment by chuanjiesun** [comment] 2016-12-08 00:57
the libpcap version is "libpcap-devel-1.4.0-4.20130826git2dbcaa1.el6.x86_64",is that too old ?  and I will send an email to VPS provider to see if packet filters are disabled.

**Comment by nothingsec** [comment] 2017-04-08 13:16
Did you solve the problem now?Is it the question of BandwagonHost?

**Comment by chuanjiesun** [comment] 2017-04-10 05:15
yes,it  can't run openvz, and it runs well on kvm vps.



chuanjiesun@gmail.com
 
From: nothingsec
Date: 2017-04-08 21:16
To: zmap/zmap
CC: chuanjiesun; Author
Subject: Re: [zmap/zmap] zmap can't run on BandwagonHost VPS (#398)
Did you solve the problem now?Is it the question of BandwagonHost?

**Comment by nothingsec** [comment] 2017-04-10 07:38
thanks！
发自网易邮箱大师
On 04/10/2017 13:15, chuanjiesun wrote: yes,it  can't run openvz, and it runs well on kvm vps.







chuanjiesun@gmail.com

  

From: nothingsec

Date: 2017-04-08 21:16

To: zmap/zmap

CC: chuanjiesun; Author

Subject: Re: [zmap/zmap] zmap can't run on BandwagonHost VPS (#398)

Did you solve the problem now?Is it the question of BandwagonHost?

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zmap/zmap","title":"zmap/zmap","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zmap/zmap"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chuanjiesun in #398: yes,it  can't run openvz, and it runs well on kvm vps.\r\n\r\n\r\n\r\nchuanjiesun@gmail.com\r\n \r\nFrom: nothingsec\r\nDate: 2017-04-08 21:16\r\nTo: zmap/zmap\r\nCC: chuanjiesun; Author\r\nSubject: Re: [zmap/zmap] zmap can't run on BandwagonHost VPS (#398)\r\nDid you solve the problem now?Is it the question of BandwagonHost?\r\n—\r\nYou are receiving this because you authored the thread.\r\nReply to this email directly, view it on GitHub, or mute the thread.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/zmap/zmap/issues/398#issuecomment-292851725"}}}

**Comment by zakird** [comment] 2017-09-15 18:48
This is effectively a duplicate of #316, which I closed. Discussion in that issue.

**Closed by zakird** 2017-09-15 18:48 UTC
Labels: support
