### ISSUE TITLE
hitrate below 0 for 1442094080 seconds. aborting scan

### ISSUE THREAD

**Issue by frkay** [zmap/zmap#289] opened 2015-09-12 21:51 UTC
Hello,
I've build version 2.1.1 from source on Linux Ubuntu 14.04, but I always get this error when run:
Sep 12 23:48:54.749 [INFO] csv: no output file selected, will use stdout
Sep 12 23:48:54.772 [FATAL] monitor: hitrate below 0 for 1442094592 seconds. aborting scan.

**Comment by dadrian** [comment] 2015-09-12 22:44
This may be caused by a bad floating point comparison, which should have been fixed in https://github.com/zmap/zmap/commit/924da2fc30f609b2e8e7b686707adc012322b941. Can you try building the latest version of master, and see if this still occurs?

**Comment by zakird** [comment] 2015-09-13 00:31
I don't believe this is broken in 2.1.1 tag, but it was in master. I've reverted the commit that causes the problem. 99f9ae190c87f0a4954b4878151d51d20973baba

**Comment by Zone-Tan** [comment] 2015-09-13 15:37
zakird, yestardnay i have the same issue...
In vost current master problem are gone.
(tested 5 min ago)

**Comment by zakird** [comment] 2015-09-13 16:36
Thanks! This fixed things on our end as well, so I'm going to go ahead and close this issue. If anyone still has the problem, please feel free to reopen.

**Closed by zakird** 2015-09-13 16:36 UTC
Labels: bug
