### ISSUE TITLE
Ubuntu 14.10: ZMap not capturing responses

### ISSUE THREAD

**Issue by sheharbano** [zmap/zmap#274] opened 2015-06-23 22:31 UTC
I just built ZMap from source, conducted a scan and found that it does not capture 
responses even though tcpdump shows them. 

My scan command is:
./src/zmap -i eth0 -p 80

The machine is:
Ubuntu 14.10
Linux 3.16.0-23-generic #31-Ubuntu SMP 

Repo head is:
ac5ba73883f88e7f6f04cd03a79ed471875723f4

and here is the tail of monitor log:

Jun 23 23:12:29.339 [WARN] monitor: Dropped 1 packets in the last second, (4 total dropped (pcap: 0 + iface: 4))
 0:07 0% (7h00m left); send: 1020658 145 Kp/s (145 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
 0:08 0% (6h59m left); send: 1166155 145 Kp/s (145 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
Jun 23 23:12:31.339 [WARN] monitor: Dropped 1 packets in the last second, (5 total dropped (pcap: 0 + iface: 5))
 0:09 0% (6h59m left); send: 1311749 146 Kp/s (145 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%

-------------------------------------
Please note that using the same command and ZMap, I was able to scan just
fine from another machine:

Red Hat Enterprise Linux Server release 6.6 (Santiago)
Linux 2.6.32-504.3.3.el6.x86_64 #1 SMP

**Comment by zakird** [comment] 2015-06-23 23:51
Can you give us a little more information about the packets or provide us
with a PCAP and relevant parameters? Did these packets belong to the scan?
It's hard to act on this amount of information.

**Comment by sheharbano** [comment] 2015-06-24 06:32
​
 pcaps.tar.gz
<https://drive.google.com/file/d/0B3IsQVtnnNFPNUh6RWY3X2ZpMDg/edit?usp=drive_web>
​

> Can you give us a little more information about the packets or provide us
> with a PCAP and relevant parameters?
>

Sure. Please find attached two pcap files. In both cases, the following
commands
were used:

command: tcpdump -i eth0 'port 80' -w <pcap file>
ZMap command: ./src/zmap -i eth0 -p 80

zmap_recent.pcap is with ZMap built from the current master

zmap_9a7ac3d31d4672b526dc2265150019393610177f.pcap is from the same
machine, but I checked out an older branch
(9a7ac3d31d4672b526dc2265150019393610177f)

Please note that the latter works fine, that is, ZMap logs responses as
expected.

-- 
--Bano

**Comment by dadrian** [comment] 2015-06-26 18:13
Based on the pcap files, it looks like the problem is the responses are not coming back from the gateway, and in between current master and 9a7ac3d (specifically, commit 4131369d571df24e14f95b8829d688a30bb2847d), we edited the pcap filter to only accept recv traffic from the gateway (see https://github.com/zmap/zmap/blob/master/src/recv-pcap.c#L64).

I've discussed this with @zakird before, we should probably change the pcap filter to be "not (src mac <outgoing MAC address>) and <proble module filter>", rather than "src mac <gateway MAC address> and <probe module filter>".

@zakird, @amirian28, @hmoore-r7 thoughts?

**Comment by hmoore-r7** [comment] 2015-06-26 19:46
The ``not (src mac <outgoing mac address>) and <probe module filter>`` change might work, but it wasn't clear if we stored this anywhere today, and it might break with ``balance-rr`` interface bonding setups where each outbound packet is round-robined between NICs.

**Comment by hmoore-r7** [comment] 2015-06-26 19:48
Maybe we enable a flag to flip between ```(from gateway|not from source)``` modes? The ``balance-rr`` issue may be less prevalent than multi-path routing where packets back from a different gateway.

**Comment by zakird** [comment] 2015-06-26 19:54
we do store outgoing MAC, because ZMap sets it on outgoing ethernet frames.
I'm not sure if balance-rr is an issue. We manually set the source MAC on
all outgoing packets---would this already have broken round robin? Does
balance-rr do raw sockets?

**Comment by zakird** [comment] 2015-06-30 19:32
This should be fixed by dacc2e0. @sheharbano, please confirm and we'll merge to stable.

**Comment by hmoore-r7** [comment] 2015-06-30 19:37
Looks like ``balance-rr`` is not going to be relevant since zmap just injects directly (and is pegged to an interface). Thanks!

**Comment by zakird** [comment] 2015-07-06 12:03
I'm closing for now since no response and merging to stable. Please feel free to re-open if issue persists.

**Closed by zakird** 2015-07-06 12:03 UTC
Labels: bug
