### ISSUE TITLE
Same Seed in Ziterate and Zmap does not produce same subset of IP addresses

### ISSUE THREAD

**Issue by ajholland** [zmap/zmap#523] opened 2018-05-18 17:54 UTC
<img width="661" alt="screen shot 2018-05-18 at 1 34 30 pm" src="https://user-images.githubusercontent.com/6451295/40249935-a3123e5c-5aa2-11e8-9c12-5368004da061.png">

The use-case here would be to generate a list of IP's before sending. I could do so with dry-run mode but if I only want the IP's it's just another step to have to filter those out. I would expect ZIterate to match the same list of IP addresses that ZMap would produce since they are initialized with the same seed.

**Comment by jhart-r7** [comment] 2018-05-21 18:54
Weird, I can't reproduce.  I had to fire up zmap differently but wrt the seed and cyclic generator things should be the same:

```
$  ./src/zmap -p 443 -i en0 -e 1 -T 1  -r 10000  -d -G 00:00:00:00:00:00 -n 2  2>&1 |grep "^ip" |awk '{print $7}'
19.177.208.109
236.168.140.25
[ jhart@LAX-MBP-1576 (05/21/18 11:53:25) ~/rapid7/zmap  ]                                                                                                                                                       
$  ./src/ziterate -e 1 -n 2                                                                                                            
19.177.208.109
236.168.140.25
```

**Comment by zakird** [comment] 2019-03-28 23:17
I'm not able to confirm this on linux or mac os for master. Closing.

**Closed by zakird** 2019-03-28 23:17 UTC
