### ISSUE TITLE
Dropped packets

### ISSUE THREAD

**Issue by ghost** [zmap/zmap#355] opened 2016-07-11 11:34 UTC
Hi,

i try using zmap with the below listed cmd on ubuntu and centos and on both i get the same errors.

It's dropping packets and when the scan is done, it goes in a loop for 135y lol

I'd highly appreciate any input that can help me resolve the issue. I've already lowered the -r and -P flags but the result is the same. With lower value it scan slower but eventually the error returns.

Used cmd: zmap -p 53 -M udp --probe-args=file:access-board.gov.pkt -w 53awk.txt -r 1000 -P 100 -s 1153 -i eth0 | tcpdump -q -n -s 8000 -i eth0 'udp dst port 1153 and not src XX.YY.XX.YY'|awk '{print substr($3,0,length($3)-3) " " $8}' > 53dump.txt

![error](https://cloud.githubusercontent.com/assets/15252503/16729285/1bb9058c-4774-11e6-8a19-e5a629a3660f.png)

PCAP using tcpdump -nnXSs 0 'port 1153' -w zmap.pcap
https://mega.nz/#!P4IVHaYQ!LNggxcpV6wE0_aTa3uVqph-g6IMhE2oMzlUfLl7vAU0

Thanks :+1:

**Comment by zakird** [comment] 2016-07-12 05:44
What Version of ZMap are you running? IF you're not on master, can you please confirm that the problem still exists on master?

**Comment by zakird** [comment] 2016-07-12 05:44
On Mon, Jul 11, 2016 at 4:34 AM, GreenOut <notifications@github.com> wrote:

> zmap -p 53 -M udp --probe-args=file:access-board.gov.pkt -w 53awk.txt -r
> 1000 -P 100 -s 1153 -i eth0
>

What Version of ZMap are you running? IF you're not on master, can you
please confirm that the problem still exists on master?

**Comment by dadrian** [comment] 2016-07-12 05:45
Have you tried running it without the call to tcpdump?

**Comment by GreenOut** [comment] 2016-07-12 05:47
Hi,

without tcpdump it's the same issue. I'm running the latest version i believe 2.1.1

**Comment by zakird** [comment] 2016-07-12 05:48
There's not much we can do about the dropped packets---it looks like your hardware isn't keeping up. However, I would like to track down what's causing ZMap to go into the long loop towards the end. Would you be willing to test on master?

**Comment by GreenOut** [comment] 2016-07-12 05:59
The CPU is barely used. I can provide you access to the server if you like. Sent me your ssh key per email at pavel (at) youboot.net

**Comment by dadrian** [comment] 2016-07-12 06:03
It's much more likely a NIC issue than a CPU issue.

**Comment by GreenOut** [comment] 2016-07-12 06:46
Tested it on a much larger, better server and i get the same issue. First it drops a bunch of packets and then it goes into the long loop.

1:38 101% (0s left); send: 88125 done (988 p/s avg); recv: 4632 0 p/s (47 p/s avg); drops: 332 p/s (5.02 Kp/s avg); hitrate: 5.26%
Jul 12 06:45:28.336 [WARN] monitor: Dropped 707 packets in the last second, (492813 total dropped (pcap: 492813 + iface: 0))

(As you can see it's already 101% and it continues)

**Comment by GreenOut** [comment] 2016-07-12 08:22
I don't care as much about the dropped packets than about the long loop in the end. Would be great if someone can fix that.

**Comment by GreenOut** [comment] 2016-07-12 10:33
Tested master and this long-loop still happens!!

**Comment by zakird** [comment] 2016-07-12 16:05
OK, thanks for testing. I've marked as a bug and we'll investigate.

**Comment by zakird** [comment] 2016-07-12 16:06
`zmap -p 53 -M udp --probe-args=file:access-board.gov.pkt -w 53awk.txt -r 1000 -P 100 -s 1153 -i eth0 | tcpdump -q -n -s 8000 -i eth0 'udp dst port 1153 and not src XX.YY.XX.YY'|awk '{print substr($3,0,length($3)-3) " " $8}' > 53dump.txt`

Do I understand correctly that you're trying to send each host 1000 packets?

**Comment by GreenOut** [comment] 2016-07-12 16:11
Hello,

i try with much lower values but due to the fact that we need -P 100 for a good scan result, using -r 1000 seemed to be reasonable.

however i used even just -r 10 but the error would still persist.

**Comment by GreenOut** [comment] 2016-07-14 14:41
Hey,

is there any development on that issue? I'll make a donation if the bug can be fixed swiftly because i really need zmap to work for me.

Cheers

**Comment by GreenOut** [comment] 2016-07-29 12:26
`zmap -p 53 -M udp --probe-args=file:access-board.gov.pkt -I 53awk.txt -s 1153 -P100 -i $nic >/dev/null &
( tcpdump -q -n -s 8000 -i $nic 'udp dst port 1153 and not src ${ipaddress}' | gawk '/bad length/{print substr($3,0,(length($3)-3)) " " $9; next} {print substr($3,0,(length($3)-3)) " " $8}' > 53dump.txt`

Not sure what caused the loop in the end but _it works like a charm now_. If anyone is interested, i can share the auto-scan/filter script.

**Closed** 2016-08-31 17:26 UTC
Labels: bug

**Comment by zirngibl** [comment] 2021-01-14 11:28
Hi,

even though this issue is closed for a couple of years now, I think we ran into the same or at least a similar issue with the current master branch.

We piped the output of ZMap into further scripts (without ZTee). Apparently these scripts stopped reading from the pipe at some point and ZMap started to dropped incoming packets. We assume ZMap drops all incoming packets if it is not able to write output anymore without reducing the sending rate thus the ETA reduces. After the ETA reaches 0 it starts with 4294967295 

`
2021-01-14 11:09:29,24,0,102.891378,0.280165,0,261632,19148,19515,733,0,30,8936,0,371,929,0,39,0,0,0
`
`
2021-01-14 11:09:30,25,4294967295,107.165579,0.280165,0,261632,19148,19515,733,0,29,8936,0,356,929,0,37,0,0,0
`

We were able to reproduce this by simply piping the ZMap output to more (https://linux.die.net/man/1/more) waiting for the screen to fill without advancing the output. We did a simple TCP Syn scan with port 443 and a /14 prefix containing more than the 733 shown results with a rate of 20000 pps.

While we think can handle this by using ZTee and improving our own script, we thought you might be interested.
