### ISSUE TITLE
PFring Zmap

### ISSUE THREAD

**Issue by neginsadeghi** [zmap/zmap#695] opened 2022-07-11 08:29 UTC
I followed the steps that you said on install page, at final I got the following error, please help me to find out what is the problem : 

  319  git clone https://github.com/zmap/zmap
  320  cd zmap/
  328  apt-get install software-properties-common wget
  329  add-apt-repository universe
  330  wget https://packages.ntop.org/apt/20.04/all/apt-ntop.deb
  331  apt install ./apt-ntop.deb
  332  apt update
  333  sudo chown _apt /var/lib/update-notifier/package-data-downloads/partial/
  343  apt install pfring-drivers-zc-dkms
  356  sudo apt-get install libnuma-dev
  357  cmake -DWITH_PFRING=ON -DENABLE_DEVELOPMENT=OFF . && make -j4 && make install
  360  sudo ./src/zmap -p 80 -i zc:ens160 -o output.csv -T 5

The error : 

root@ZmapTestPfring:~/zmap# sudo ./src/zmap -p 80 -i zc:ens160 -o output.csv -T 5

Jul 11 08:28:17.299 [FATAL] zmap: Could not create zc cluster: No buffer space available

**Comment by dadrian** [comment] 2022-08-02 00:33
Duplicate of #694

**Closed by dadrian** 2022-08-02 00:33 UTC
Labels: bug
