### ISSUE TITLE
[FATAL] zmap: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Pablohn26** [zmap/zmap#296] opened 2015-09-27 00:59 UTC
Because a typo (zmap instead of nmap) I have gotten a segmentation fault when you run 
    
    zmap -O example.com

would be interesting to improve the deal of arguments

**Comment by dadrian** [comment] 2015-09-27 01:54
Agreed, that should definitely not happen. @paul-pearce, if you're sitting in the code still it'd be great if you could investigate, it looks like we just have an out-of-bounds index in the selection of the output modules.

**Comment by paul-pearce** [comment] 2015-09-29 01:53
What version?

**Comment by zakird** [comment] 2015-09-29 02:23
Can you please confirm that this is happening in the master branch? I am able to confirm on older versions, but this seems to be fixed in master.

**Comment by zakird** [comment] 2015-09-29 02:24
This is the bt on older versions: https://gist.github.com/zakird/32691310090c8375e651

**Comment by zakird** [comment] 2016-01-17 21:42
I am closing this issue as there has been no additional information from the reporter on how to reproduce the bug.

**Closed by zakird** 2016-01-17 21:42 UTC
Labels: bug

**Comment by Pablohn26** [comment] 2016-01-17 22:32
Sorry about the delay. It was and old version (1.2.1). Tested and fixed on latest version.
